### ISSUE TITLE
User-defined type not defined

### ISSUE THREAD

**Issue by CinnamonLover** [lauxjpn/CurruptQueryAccessWorkaround#1]
When I try to run this, I get a "User-defined type not defined." I'll admit, I have very little experience with modules, so it's likely that I'm doing something wrong. Do you have any ideas?

https://github.com/CinnamonLover/probable-sniffle/blob/master/CorruptQueryWorkaround.PNG

**Comment by lauxjpn** [comment]
`TableDef` and the other types are part of `DAO`, so you will need to ensure that the DAO reference is set under `VBA Editor -> Tools -> References`.

For backward compatibility with older Versions of Access (2003 and before), the `Microsoft DAO 3.6 Object Library` needs to be added (selected line in the screenshot):

![image](https://user-images.githubusercontent.com/14178357/70460946-c7b3ad00-1ab7-11ea-8595-eec4dbf45f25.png)

If you only need to support a single newer version of Access (2007 and later), you can use the newer `Microsoft Office x.x Access Database Engine Object Library` reference instead:

![image](https://user-images.githubusercontent.com/14178357/70461233-81ab1900-1ab8-11ea-8dcd-37c37d86351a.png)

---

The next Microsoft Patch Day is tomorrow (2019-12-10) and the [fixes that Microsoft released](https://support.office.com/en-us/article/access-error-query-is-corrupt-fad205a5-9fd4-49f1-be83-f21636caedec) 2-3 weeks ago will be shipped automatically.

So you might not need to implement the workaround anymore.
